using System;
using System.Collections.Generic;
using Crestron.SimplSharp;
using Newtonsoft.Json;


namespace TSI.FourSeries.PresetManagement
{
    public class PresetManagement
    {
        Root root = new Root();
        FileOperations fileOps = new FileOperations();
        string filecontents;
        string _filelocation;

        public string fileLocation
        {
            get { return _filelocation; }
            set { _filelocation = value; }
        }


        public PresetManagement()
        {
            //emtpy initializer
        }

        /// <summary>
        /// this method is the only one exposed to simpl+ because it is public and the others are private. This method, when successful in reading the file, will in turn, call the others, so it need not be exposed.
        /// </summary>
        public void Initialize()
        {
            if (FileOperations.CheckFileExists(_filelocation))
            {
                filecontents = FileOperations.ReadFile(_filelocation);
                CrestronConsole.PrintLine("fileContents: {0}", filecontents.ToString());
            }
            else
            {
                if (Debug.debugEnable) CrestronConsole.PrintLine(Constants.FileNotFoundCreatingNewFileMessage, _filelocation);

                //create a default json string
                try
                {
                    string jsonTemplate = String.Format(Constants.DefaultFileContents);
                    if (Debug.debugEnable) CrestronConsole.PrintLine(jsonTemplate);

                    //Write default string to file
                    FileOperations.WriteFile(_filelocation, jsonTemplate);

                    //Read file
                    filecontents = FileOperations.ReadFile(_filelocation);

                }
                catch (Exception ex)
                {
                    CrestronConsole.PrintLine(Constants.InitializeExceptionMessage, ex.Message);
                }
            }

            DeserializeJSON();
            

        }

        
        /// <summary>
        /// This method is called after the file is successfully read. It will deserialize the file contents into a collection of objects. These objects are difined in the "Structures.cs" class. 
        /// The objects in structures.cs can be automatically generated by running your json file through www.json2csharp.com.
        /// </summary>
        private void DeserializeJSON()
        {
            try
            {
                if (!filecontents.Equals(String.Empty) && !filecontents.Equals(null))
                {
                    root = JsonConvert.DeserializeObject<Root>(filecontents);
                    GetPresetListFromFile();
                }
                else
                {
                    CrestronConsole.PrintLine(Constants.NothingToDeserializeMessage);
                }
            }
            catch (Exception e)
            {
                ErrorLog.Error(Constants.ErrorConvertingFileContentsMessage, filecontents, e.Message);
                CrestronConsole.PrintLine(Constants.ErrorConvertingFileContentsMessage, filecontents, e.Message);
            }
        }

        
        /// <summary>
        /// This is a generic type of event in which we loop thru whatever object is in the json file. As we loop, we populate a custom Eventargs and then raise an event with those EventArgs. This event 
        /// is monitored by simpl+ and serves as our means of receiving the pertinent info from this class.
        /// </summary>
        private void GetPresetListFromFile()
        {
            if (!root.presets.Count.Equals(0))
            {
                try
                {
                    //for loop to iterate through passwords
                    for (int i = 0; i < root.presets.Count; i++)
                    {
                        //create empty event args of type pwListCodeEventArgs
                        PresetListLoadedEventArgs args = new PresetListLoadedEventArgs()
                        {
                            presetindex = (ushort)(i + 1),
                            presetname = root.presets[i].name,
                            presetnumber = root.presets[i].number,
                            presetband = root.presets[i].band
                        };

                        if (!PresetListLoadedEventToCall.Equals(null))
                        {
                            PresetListLoadedEventToCall(this, args);
                        }
                    }
                }
                catch (Exception e)
                {
                    CrestronConsole.PrintLine(Constants.GetPresetListFromFileExceptionStackTrace, e.Message);
                }
            }
        }

        // This is the event to raise when a preset is parsed out. Simpl+ is monitoring this event
        public event EventHandler<PresetListLoadedEventArgs> PresetListLoadedEventToCall;
    }





}
