namespace TSI.FourSeries.DisplayPresetManagement
{
    using System;
    using Crestron.SimplSharp;
    using Newtonsoft.Json;
    

    public class DisplayPresetManagement
    {
        private Root root = new Root();

        private string filecontents;
        private string filelocation;


        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayPresetManagement"/> class.
        /// </summary>
        public DisplayPresetManagement()
        {

        }

        // This is the event to raise when a preset is parsed out. Simpl+ is monitoring this event
        public event EventHandler<PresetListLoadedEventArgs> PresetListLoadedEventToCall;


        /// <summary>
        /// Gets or Sets FileLocation
        /// </summary>
        public string FileLocation
        {
            get { return this.filelocation; }
            set { this.filelocation = value; }
        }

        /// <summary>
        /// this method is the only one exposed to simpl+ because it is public and the others are private. This method, when successful in reading the file, will in turn, call the others, so it need not be exposed.
        /// </summary>
        public void Initialize()
        {
            if (FileOperations.CheckFileExists(filelocation))
            {
                filecontents = FileOperations.ReadFile(filelocation);
                CrestronConsole.PrintLine("fileContents: {0}", filecontents.ToString());
            }
            else
            {
                if (Debug.debugEnable) CrestronConsole.PrintLine(Constants.FileNotFoundCreatingNewFileMessage, filelocation);

                //create a default json string
                try
                {
                    string jsonTemplate = Constants.DefaultFileContents;
                    if (Debug.debugEnable) CrestronConsole.PrintLine(jsonTemplate);

                    //Write default string to file
                    FileOperations.WriteFile(filelocation, jsonTemplate);

                    //Read file
                    filecontents = FileOperations.ReadFile(filelocation);

                }
                catch (Exception ex)
                {
                    CrestronConsole.PrintLine(Constants.InitializeExceptionMessage, ex.Message);
                }
            }

            DeserializeJSON();
            

        }

        public void SetDebug(ushort flag)
        { 
            Debug.SetDebug(flag);
        }

        /// <summary>
        /// the following two methods were added 11-2-21 and tested on 11-8-21
        /// OverwritePreset will overwrite the preset info for a given index.
        /// WriteLocalListToFile() will write the updated preset list to the file.
        /// </summary>
        public void OverwritePreset(ushort index, string newInput, ushort newStream, string newChannel)
        {
            Preset preset = new Preset()
            {
                input = newInput,
                stream = newStream,
                channel = newChannel
            };

            try
            {
                if (index < root.presets.Count)
                {
                    root.presets[index] = preset;
                }
                else
                {
                    root.presets.Add(preset);
                }
            }
            catch (Exception e)
            {
                CrestronConsole.PrintLine(Constants.OverwritePresetExceptionStackTrace, e.Message);
            }
        }

        /// <summary>
        /// Write the List to file
        /// </summary>
        public void WriteLocalListToFile()
        {

            var UpdatedJson = JsonConvert.SerializeObject(root);
            FileOperations.WriteFile(filelocation, UpdatedJson);
        }

        /// <summary>
        /// This method is called after the file is successfully read. It will deserialize the file contents into a collection of objects. These objects are difined in the "Structures.cs" class. 
        /// The objects in structures.cs can be automatically generated by running your json file through www.json2csharp.com.
        /// </summary>
        private void DeserializeJSON()
        {
            try
            {
                if (!filecontents.Equals(String.Empty) && !filecontents.Equals(null))
                {
                    root = JsonConvert.DeserializeObject<Root>(filecontents);
                    GetPresetListFromFile();
                }
                else
                {
                    CrestronConsole.PrintLine(Constants.NothingToDeserializeMessage);
                }
            }
            catch (Exception e)
            {
                ErrorLog.Error(Constants.ErrorConvertingFileContentsMessage, filecontents, e.Message);
                CrestronConsole.PrintLine(Constants.ErrorConvertingFileContentsMessage, filecontents, e.Message);
            }
        }


        /// <summary>
        /// This is a generic type of event in which we loop thru whatever object is in the json file. As we loop, we populate a custom Eventargs and then raise an event with those EventArgs. This event 
        /// is monitored by simpl+ and serves as our means of receiving the pertinent info from this class.
        /// </summary>
        private void GetPresetListFromFile()
        {

            if (!root.presets.Count.Equals(0))
            {
                try
                {
                    //for loop to iterate through presets
                    for (int i = 0; i < root.presets.Count; i++)
                    {
                        //create empty event args of type pwListCodeEventArgs
                        PresetListLoadedEventArgs args = new PresetListLoadedEventArgs()
                        {
                            presetindex = (ushort)(i + 1),
                            presetinput = root.presets[i].input,
                            presetstream = root.presets[i].stream,
                            presetchannel = root.presets[i].channel
                        };

                        //call eventhandler
                        if (!PresetListLoadedEventToCall.Equals(null))
                        {
                            PresetListLoadedEventToCall(this, args);
                        }
                    }
                }
                catch (Exception e)
                {
                    CrestronConsole.PrintLine(Constants.GetPresetListFromFileExceptionStackTrace, e.Message);
                }
            }
        }



    }





}
